### ISSUE TITLE
DetailedUsageFragment Error 

### ISSUE THREAD

**Issue by Gaebobman** [BBSSJJ/CarbonCheck#34]
`FATAL EXCEPTION: main
                                                                                                    Process: kr.co.carboncheck.android.carboncheckapp, PID: 31370
                                                                                                    java.lang.NullPointerException
                                                                                                    	at kr.co.carboncheck.android.carboncheckapp.view.DetailedUsageFragment.inflateCardView(DetailedUsageFragment.kt:54)
                                                                                                    	at kr.co.carboncheck.android.carboncheckapp.view.DetailedUsageFragment.onCreateView(DetailedUsageFragment.kt:36)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by Gaebobman** [comment]
해석: java.lang.NullPointerException: null 값을 가진 객체에 접근하려고 할 때 발생하는 예외임
DetailedUsageFragment.kt Line 54 에서 null 값을 가진 객체에 접근하려고 했기 때문에 예외가 발생하였음.

해결 방법: null 값을 가진 객체에 접근하지 않도록 코드를 수정 하면 됨
예를 들어, null 체크를 하거나, 안전한 호출 연산자(?.)나 엘비스 연산자(?:)를 사용
https://kotlinlang.org/docs/null-safety.html

**Comment by BBSSJJ** [comment]
`ed0b0772c7633be5bc04597ba68175c6ac7f45d2`
