### ISSUE TITLE
TotlaUsageFragment Error

### ISSUE THREAD

**Issue by BBSSJJ** [BBSSJJ/CarbonCheck#41]
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.co.carboncheck.android.carboncheckapp, PID: 5609
    java.lang.IllegalStateException: Fragment TotalUsageFragment{2ec5447} (a875bae1-7d31-4975-bfa0-3b9fc46ac6b9) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
        at kr.co.carboncheck.android.carboncheckapp.view.TotalUsageFragment.fillDonutInitialData(TotalUsageFragment.kt:134)
        at kr.co.carboncheck.android.carboncheckapp.view.TotalUsageFragment.onViewCreated$lambda$1(TotalUsageFragment.kt:77)
        at kr.co.carboncheck.android.carboncheckapp.view.TotalUsageFragment.$r8$lambda$o3oOw4AcNL5ET3PZWQfSwAbQVyQ(Unknown Source:0)
        at kr.co.carboncheck.android.carboncheckapp.view.TotalUsageFragment$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

**Comment by Gaebobman** [comment]
Fixed:  1a5c735866bf9b6a4a7efb4acf0d1425f4425731

원인:  Fragment가 Activity에 Attach되지 않았을 때 context를 호출 하였기 때문임

해결법
onAttach에서 인자로 받은 context를 사용하면 된다
```kotlin
class TotalUsageFragment : Fragment() {
    ....
    private lateinit var myContext :Context    // myContext를 lateinit 으로 선언
    ...
    
    override fun onAttach(context: Context) {
        super.onAttach(context)
        myContext = context
    }
    
   //  ...
    
        private fun fillDonutInitialData(donutProgressView: DonutProgressView) {
        val context = myContext    // onAttach의 context 사용
        if (context != null) {
            val sections = listOf(
                DonutSection(
                    ElectricCategory.name,
                    ContextCompat.getColor(context, R.color.electric),
                    electricAmount
                ),
                DonutSection(
                    WaterCategory.name,
                    ContextCompat.getColor(context, R.color.water),
                    waterAmount
                )
            )
            donutProgressView.submitData(sections)
        }
    }
    
    // ...
    
}
```
